media: src/assets
content:
  - name: projects
    label: Projects
    path: src/content/projects
    type: collection
    view:
      fields: [ title, company ]
    fields: 
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: order
        label: Order
        type: number
      - name: company
        label: Company
        type: string
      - name: thumbnail
        label: Thumbnail
        type: image
      - name: body
        label: Body
        type: rich-text