content:
  - name: projects
    label: Projects
    path: src/content/projects
    type: collection
    fields: 
      - name: title
        type: string
      - name: description
        type: string
      - name: order
        type: number