content:
  - name: projects
    label: Projects
    path: src/content/projects
    type: collection
    view:
      fields: [ title, description, order ]
    fields: 
      - name: title
        type: string
      - name: description
        type: string
      - name: order
        type: number
      - name: body
        label: Body
        type: rich-text